#!/usr/bin/env python3

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run the Sopaper Evidence helper pipeline: build evidence ledger, bootstrap claim map, "
            "and generate an experiment gap report."
        )
    )
    parser.add_argument(
        "--sources",
        nargs="+",
        required=True,
        help="Source markdown/text files used to build the evidence ledger.",
    )
    parser.add_argument(
        "--claims",
        required=True,
        help="Markdown file containing candidate claims.",
    )
    parser.add_argument(
        "--output-dir",
        default="output/evidence-pipeline",
        help="Directory for generated outputs. Default: output/evidence-pipeline",
    )
    parser.add_argument(
        "--prefix",
        default="draft",
        help="Filename prefix for generated files. Default: draft",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parent.parent
    sources = [Path(value).expanduser().resolve() for value in args.sources]
    claims = Path(args.claims).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    missing = [str(path) for path in sources + [claims] if not path.exists()]
    if missing:
        for item in missing:
            print(f"Missing input: {item}", file=sys.stderr)
        return 1

    ledger_path = output_dir / f"{args.prefix}-ledger.md"
    claim_map_path = output_dir / f"{args.prefix}-claim-map.md"
    gap_report_path = output_dir / f"{args.prefix}-gap-report.md"
    summary_path = output_dir / f"{args.prefix}-summary.md"

    run_python(
        root / "scripts" / "build_evidence_ledger.py",
        [str(path) for path in sources] + ["-o", str(ledger_path)],
    )
    run_python(
        root / "scripts" / "bootstrap_claim_map.py",
        [str(claims), str(ledger_path), "-o", str(claim_map_path)],
    )
    run_python(
        root / "scripts" / "triage_evidence_gaps.py",
        [str(claims), str(ledger_path), "-o", str(gap_report_path)],
    )

    write_summary(
        summary_path=summary_path,
        sources=sources,
        claims=claims,
        ledger_path=ledger_path,
        claim_map_path=claim_map_path,
        gap_report_path=gap_report_path,
    )

    print("Pipeline complete.")
    print(f"summary: {summary_path}")
    print(f"ledger: {ledger_path}")
    print(f"claim_map: {claim_map_path}")
    print(f"gap_report: {gap_report_path}")
    return 0


def run_python(script: Path, arguments: list[str]) -> None:
    subprocess.run(
        [sys.executable, str(script), *arguments],
        check=True,
    )


def write_summary(
    *,
    summary_path: Path,
    sources: list[Path],
    claims: Path,
    ledger_path: Path,
    claim_map_path: Path,
    gap_report_path: Path,
) -> None:
    lines = [
        "# Evidence Pipeline Summary",
        "",
        "This summary was generated by `scripts/run_evidence_pipeline.py`.",
        "",
        "## Inputs",
        "",
        f"- Claims file: `{claims}`",
    ]

    for source in sources:
        lines.append(f"- Source file: `{source}`")

    lines.extend(
        [
            "",
            "## Outputs",
            "",
            f"- Ledger draft: `{ledger_path}`",
            f"- Claim map draft: `{claim_map_path}`",
            f"- Gap report draft: `{gap_report_path}`",
            "",
            "## Review checklist",
            "",
            "- Replace placeholder `TODO:` statements in the ledger with reviewed summaries.",
            "- Verify all external sources before using them for paper claims.",
            "- Remove or narrow unsupported claims in the claim map.",
            "- Resolve blocker and major gaps before drafting paper text.",
            "",
            "## Next step",
            "",
            "After reviewing these drafts, continue with the evidence brief, related work matrix, and paper outline workflow.",
            "",
        ]
    )

    summary_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
